name: Godot Deploy New Action

on:
    push:
        branches:
            - cd_ci_test
            - dev
    workflow_dispatch:
        inputs:
            version-name: 
                required: true
            version-tag:
                required: true
                type: choice
                options:
                - alpha
                - beta
                - release

jobs:
    download-godot:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository (To Get Local Action)
              uses: actions/checkout@v3

            - name: Download and Cache Godot Engine + Templates
              uses: ./.github/actions/download_godot
    
   
    compile_all_platforms_dispatch:
      
      env:
        game-name: "Bittify"
        version: ${{inputs.version-name}}-${{inputs.version-tag}}
      needs: download-godot
      runs-on: ubuntu-latest
      steps:

        - name: Compiling for All Available Platforms
          uses: ./.github/workflows/all_platform_comp.yml
          with:
            version-number: ${{env.version}}
    compile_all_platforms_canary:
      
      env:
        game-name: "Bittify-canary-${{github.sha}}"
        version: "dev-build-${{github.sha}}"
      needs: download-godot
      runs-on: ubuntu-latest
      steps:
        - name: Check out repository (To Get Local Action)
          uses: actions/checkout@v3

        - name: Compiling for All Available Platforms
          uses: ./.github/workflows/all_platform_comp.yml
          with:
            version-number: ${{env.version}}
            release-name: ${{env.game-name}}


   