name: Deploy-Godot

on:
  push:
    branches:
      - cd_ci_test
      - r**

jobs:
    download-godot:
      runs-on: ubuntu-latest
      steps:
        - name: Check out repository
          uses: actions/checkout@v3
        - name: Download and Cache Godot Engine + Templates
          uses: ./.github/actions/download_godot
    
    complie-game:
      needs: download-godot
      runs-on: ubuntu-latest
      strategy:
        fail-fast: false
        matrix:
          os: ["WindowsDesktop", "Linux", macOS]
      steps:
        - name: Clone Repo    
          uses: actions/checkout@v3

        - name: Restore Godot Cache
          id: cache-godot
          uses: actions/cache@v3
          with:
              path: |
                ./godot.zip
                ./templates.zip
              key: godot-downloads

        - name: List Directory
          run: ls
        
        - name: Make Directory for Export Templates
          run: mkdir -p ~/.local/share/godot/export_templates/4.0.3.stable && mkdir -p ~/builds && mkdir ~/godot

        - name: Unzip Godot
          run: unzip -j godot.zip -d ~/godot

        - name: Unzip Godot Templates
          run: unzip -j templates.zip -d ~/.local/share/godot/export_templates/4.0.3.stable
        

        - name: Check Directory
          run: ls ~/.local/share/godot/export_templates/4.0.3.stable
        
        - name: Attempt to Complie Game
          run: ~/godot/Godot_v4.0.3-stable_linux.x86_64 --path ./godot_src --headless --export-release "${{ matrix.os }}" ~/builds/bittify-${{matrix.os}}.exe
        
        - name: List builds
          run: ls ~/builds
        - name: Zip builds
          run: zip -r ${{matrix.os}}-build.zip ~/builds
        - name: Compliation Output
          uses: actions/upload-artifact@v3
          with: 
            name: Upload Complied Folder to Artifacts
            path: ${{matrix.os}}-build.zip
            retention-days: 1
        
        


        
       
   
