name: Deploy-Godot

on:
  push:
    branches:
      - cd_ci_test
      - r**
        

jobs:
    download-godot:
      name: Download Godot Engine
      runs-on: ubuntu-latest
      steps:
        - name: Download Godot
          run: wget https://downloads.tuxfamily.org/godotengine/4.0.3/Godot_v4.0.3-stable_linux.x86_64.zip -O godot.zip

        - name: Download Templates
          run: wget https://downloads.tuxfamily.org/godotengine/4.0.3/godot-lib.4.0.3.stable.template_release.aar -O templates.zip
        
        - name: Cache Downloads
          id: cache-godot
          uses: actions/cache@v3
          with:
              path: |
                ./godot.zip
                ./templates.zip
              key: godot-download
       
   
