name: Deploy-Godot

on:
  push:
    branches:
      - cd_ci_test
      - r**
        

jobs:
    build-windows:
        name: Build on Windows
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v3

            - name: Download Godot
              run:  curl https://downloads.tuxfamily.org/godotengine/4.0.3/Godot_v4.0.3-stable_win64.exe.zip --output godot.zip

            - name: Unzip Godot 
              run:  Expand-Archive .\godot.zip  
            
            - name: Echo Path
              run: ls