name: Canary-Deploy-Godot


on:
  push:
    branches:
      - cd_ci_test
      - dev
    
env:
  game-name: "Bittify-canary-${{github.sha}}"
  version: "dev-build-${{github.sha}}"

jobs:
    download-godot:
      runs-on: ubuntu-latest
      steps:
        - name: Check out repository (To Get Local Action)
          uses: actions/checkout@v3

        - name: Download and Cache Godot Engine + Templates
          uses: ./.github/actions/download_godot
    complie_linux:
      name: Compile For Linux
      uses: ./.github/workflows/godot_complie.yml
      with:
        godot-version: "4.0.3"
        version-number: "dev-canary"
        release-name: "Bittify"
        cfg-release-name: "Linux"
        platform-release-extension: "x86_64"
    
    complie_windows:
      name: Compile For Windows
      uses: ./.github/workflows/godot_complie.yml
      with:
        godot-version: "4.0.3"
        version-number: "dev-canary"
        release-name: "Bittify"
        cfg-release-name: "WindowsDesktop"
        platform-release-extension: "exe"
        
    complie_macOS:
      name: Compile For MacOS
      uses: ./.github/workflows/godot_complie.yml
      with:
        godot-version: "4.0.3"
        version-number: "dev-canary"
        release-name: "Bittify"
        cfg-release-name: "macOS"
        platform-release-extension: "zip"
   