name: Deploy-Godot

on:
  push:
    branches:
      - cd_ci_test
      - r**

jobs:
    download-godot:
      runs-on: ubuntu-latest
      steps:
        - name: Check out repository
          uses: actions/checkout@v3
        - name: Download and Cache Godot Engine + Templates
          uses: ./.github/actions/download_godot
    
    complie-game-linux:
      needs: download-godot
      runs-on: ubuntu-latest
      steps:
        - name: Check out repository
          uses: actions/checkout@v3

        - name: Prepare Godot
          uses: ./.github/actions/extract_godot

        - name: Attempt to Import all resources
          run: ~/godot/Godot_v4.0.3-stable_linux.x86_64 --path ./godot_src --headless --quit

        - name: Attempt to Complie Game
          run: ~/godot/Godot_v4.0.3-stable_linux.x86_64 --path ./godot_src --headless --export-release "Linux" ~/builds/bittify-linux.x86_64
        
        - name: Zip builds
          run: zip -r linux-build.zip ~/builds
        - name: Compliation Output
          uses: actions/upload-artifact@v3
          with: 
            name: Upload Complied Folder to Artifacts
            path: linux-build.zip
            retention-days: 1
    
    complie-game-windows:
      needs: download-godot
      runs-on: ubuntu-latest
      steps:
        - name: Check out repository
          uses: actions/checkout@v3

        - name: Prepare Godot
          uses: ./.github/actions/extract_godot

        - name: Attempt to Import all resources
          run: ~/godot/Godot_v4.0.3-stable_linux.x86_64 --path ./godot_src --headless --quit

        - name: Attempt to Complie Game
          run: ~/godot/Godot_v4.0.3-stable_linux.x86_64 --path ./godot_src --headless --export-release "WindowsDesktop" ~/builds/bittify-windows.exe
        
        - name: Zip builds
          run: zip -r windows-build.zip ~/builds
        - name: Compliation Output
          uses: actions/upload-artifact@v3
          with: 
            name: Upload Complied Folder to Artifacts
            path: windows-build.zip
            retention-days: 1
    
    complie-game-meh-os:
      needs: download-godot
      runs-on: ubuntu-latest
      steps:
        - name: Check out repository
          uses: actions/checkout@v3

        - name: Prepare Godot
          uses: ./.github/actions/extract_godot

        - name: Attempt to Import all resources
          run: ~/godot/Godot_v4.0.3-stable_linux.x86_64 --path ./godot_src --headless --quit
          
        - name: Attempt to Complie Game
          run: ~/godot/Godot_v4.0.3-stable_linux.x86_64 --path ./godot_src --headless --export-release "macOS" ~/builds/bittify-mac.zip
        
        - name: Zip builds
          run: zip -r mac-build.zip ~/builds
        - name: Compliation Output
          uses: actions/upload-artifact@v3
          with: 
            name: Upload Complied Folder to Artifacts
            path: mac-build.zip
            retention-days: 1
          

        
        


        
       
   
