name: Deploy-Godot

on:
  push:
    branches:
      - cd_ci_test
      - r**

jobs:
    download-godot:
      runs-on: ubuntu-latest
      steps:
        - name: Check out repository (To Get Local Action)
          uses: actions/checkout@v3

        - name: Download and Cache Godot Engine + Templates
          uses: ./.github/actions/download_godot
    
    complie-game-linux:
      needs: download-godot
      runs-on: ubuntu-latest
      steps:
        - name: Check out repository
          uses: actions/checkout@v3

        - name: Prepare Godot
          uses: ./.github/actions/extract_godot

        - name: Complie game
          uses: ./.github/actions/build_godot_game
          with:
            game-name: "Bittify"
          
    complie-game-windows:
      needs: download-godot
      runs-on: ubuntu-latest
      steps:
        - name: Check out repository
          uses: actions/checkout@v3

        - name: Prepare Godot
          uses: ./.github/actions/extract_godot

        - name: Complie game
          uses: ./.github/actions/build_godot_game
          with:
            game-name: "Bittify"
            release-name: "WindowsDesktop"
            release-extension: "exe"
    
    complie-game-meh-os:
      needs: download-godot
      runs-on: ubuntu-latest
      steps:
        - name: Check out repository
          uses: actions/checkout@v3

        - name: Prepare Godot
          uses: ./.github/actions/extract_godot

        - name: Complie game
          uses: ./.github/actions/build_godot_game
          with:
            game-name: "Bittify"
            release-name: "MacOS"
            release-extension: "zip"
          

        
        


        
       
   
