name: Canary-Deploy-Godot

on:
  push:
    branches:
      - cd_ci_test
      - dev

env:
  game-name: "Bittify-canary-${{github.sha}}"

jobs:
    download-godot-mehOS:
      runs-on: ubuntu-latest
      steps:
        - name: Check out repository (To Get Local Action)
          uses: actions/checkout@v3

        - name: Download and Cache Godot Engine + Templates
          uses: ./.github/actions/download_godot
          with:
            godot-build: macos.universal
    download-godot:
      runs-on: ubuntu-latest
      steps:
        - name: Check out repository (To Get Local Action)
          uses: actions/checkout@v3

        - name: Download and Cache Godot Engine + Templates
          uses: ./.github/actions/download_godot
    
    complie-game-linux:
      needs: download-godot
      runs-on: ubuntu-latest
      steps:
        - name: Check out repository
          uses: actions/checkout@v3

        - name: Prepare Godot
          uses: ./.github/actions/extract_godot

        - name: Complie game
          uses: ./.github/actions/build_godot_game
          with:
            game-name: ${{env.game-name}}
          
    complie-game-windows:
      needs: download-godot
      runs-on: ubuntu-latest
      steps:
        - name: Check out repository
          uses: actions/checkout@v3

        - name: Prepare Godot
          uses: ./.github/actions/extract_godot

        - name: Complie game
          uses: ./.github/actions/build_godot_game
          with:
            game-name: ${{env.game-name}}
            release-name: "WindowsDesktop"
            release-extension: "exe"
    
    complie-game-meh-os:
      needs: download-godot-mehOS
      runs-on: macos-latest
      steps:
        - name: Check out repository
          uses: actions/checkout@v3

        - name: Prepare Godot
          uses: ./.github/actions/extract_godot
          with:
            godot-build: macos.universal

        - name: Complie game
          uses: ./.github/actions/build_godot_game
          with:
            game-name: ${{env.game-name}}
            release-name: "macOS"
            release-extension: "zip"
          

        
        


        
       
   
