name: Deploy-Godot

on:
  push:
    branches:
      - cd_ci_test
      - r**
        

jobs:
    build-windows:
        name: Build on Windows
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v3

            - name: Download Godot
              run:  curl https://downloads.tuxfamily.org/godotengine/4.0.3/Godot_v4.0.3-stable_win64.exe.zip --output godot.zip

            - name: Unzip Godot 
              run:  Expand-Archive .\godot.zip  
            
            - name: Get Release Name
              env:
                BIT_VERSION: ${{ github.ref_name }}
              run: echo '$BIT_VERSION'
            
            - name: Change Version in Version.gd
              run: echo "extends Node" 'const VERSION = "${{ github.ref_name }}" '  > ./godot_src/version.gd
            
            - name: Echo Version.gd file contents
              run: gc ./godot_src/version.gd