name: "Download Godot Engine + Templates, extract to path"
inputs:
  godot-version:
    required: false
    default: "4.1"
  godot-build:
    required: false
    default: "linux.x86_64"

runs:
  
  using: "composite"
  steps:

    - name: Cache Downloads
      id: cache-godot
      uses: actions/cache@v3
      with:
          path: |
            ./godot.zip
            ./templates.zip
          key: godot-downloads-${{inputs.godot-version}}-${{inputs.godot-build}}

    - name: Download Godot
      if: steps.cache-godot.outputs.cache-hit != 'true'
      run: wget https://downloads.tuxfamily.org/godotengine/${{inputs.godot-version}}/Godot_v${{inputs.godot-version}}-stable_${{inputs.godot-build}}.zip -O godot.zip
      shell: bash

    - name: Download Templates
      if: steps.cache-godot.outputs.cache-hit != 'true'
      run: wget https://downloads.tuxfamily.org/godotengine/${{inputs.godot-version}}/Godot_v${{inputs.godot-version}}-stable_export_templates.tpz -O templates.zip
      shell: bash